version: 0.2

env:
  variables:
    S3_BUCKET: "cleantipsbuild"
    APP_NAME: "Cleantips"            
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install npm@latest -g
      - npm install -g @angular/cli
  pre_build:
    commands:
      - echo Prebuild steps
      - npm install
  build:
    commands:
      - ng build --prod
  post_build:
    commands:
      - aws s3 rm s3://cleantips --recursive
      - echo S3 bucket is cleared.
      - aws s3 cp dist s3://cleantips/Cleantips --recursive
      - echo Build complete on `date`
artifacts:
  files:
    - '/'
  discard-paths: yes
  base-directory: 'dist*'