version: 0.2

env:
  variables:
    S3_BUCKET: "cleantips"
    APP_NAME: "Cleantips"            
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install npm@latest -g
      - npm install -g @angular/cli
  pre_build:
    commands:
      - echo Prebuild steps
      - npm install
  build:
    commands:
      - ng build --prod
  post_build:
    commands:
      - aws s3 rm s3://${S3_BUCKET} --recursive
      - echo S3 bucket is cleared.
      - aws s3 cp dist s3://${S3_BUCKET}/${APP_NAME} --recursive
      - echo Build completed on `date`
artifacts:
  files:
    - '/'
  discard-paths: yes
  base-directory: 'dist*'